name: webapp

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: aguadamillas_students_1
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: maudhelen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  deploy:
#   if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    
    env:
      ENV: dev

    steps:

      # Checkout code
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./main.bicep
        parameters: ./parameters.json DOCKER_REGISTRY_SERVER_PASSWORD=${{secrets.DOCKER_REGISTRY_SERVER_PASSWORD }} DOCKER_REGISTRY_SERVER_USERNAME=${{vars.DOCKER_REGISTRY_SERVER_USERNAME }}
        deploymentName: ${{ env.USER_ALIAS }}
